export const REQUEST_FETCH_ANSWERS = "REQUEST_FETCH_ANSWERS";
export const FETCHED_ANSWERS = "FETCHED_ANSWERS";

export const SAVE_ANSWERS_API = "SAVE_ANSWERS_API";
export const SAVE_ANSWERS_API_FINISHED = "SAVE_ANSWERS_API_FINISHED";

export const SAVE_ANSWERS_INDEXEDDB = "SAVE_ANSWERS_INDEXEDDB";
export const SAVE_ANSWERS_INDEXEDDB_SUCCESS = " SAVE_ANSWERS_INDEXEDDB_SUCCESS"; 

export const SAVE_PAGE_ANSWERS = "SAVE_PAGE_ANSWERS";
